Repository chialab/a11ygator-app, pull requests merged in 2019-06, with the labels that each got.

#19 Enhance scheduled reports
  .env.sample
  README.md
  bin/a11ygator
  bin/subscribe.js
  bin/webhook.js
  cli/index.js
  cli/reports.js
  cli/twitter.js
  docs/cli.md
  lambda/report-enqueue/index.js
  lambda/report-schedule/index.js
  package.json
  templates/root.yml
  yarn.lock
Labels: aws, enhancement, twitter bot

#21 Possibility to includes mentions on tweets
  cli/reports.js
  lambda/report-schedule/index.js
  lambda/tweet/index.js
  templates/root.yml
Labels: enhancement, twitter bot

#24 Create a way for the user to retrieve a standalone report version on web app
  lambda/report-view/reporter.js
  public/index.js
  reporter/reporter.css
  reporter/reporter.tpl
Labels: enhancement
